### PR TITLE
feat: application title bar and sidebar

### PR DESCRIPTION
**Pull request by NektariosFifes**
Capture

**Description**

- Addition of stateful components Titlebar and SideBar
- Basic Functionality to make sure state management works as intended

**Related issue(s)**
#88

### CODE REVIEW

**Comment by NektariosFifes** [comment]
i actually did not request review. it was done automatically

**Review by jonaslagoni — DISMISSED** [review]

**Comment by jonaslagoni** [comment]
> i actually did not request review. it was done automatically. There are some things i still have to go through

Ahh okay 😄

**Comment by NektariosFifes** [comment]
i think it is ok now. i could add react component tests but i dont think it is needed yet.

**Review by jonaslagoni — APPROVED** [review]
👍

**Pull request merged**
